ALTER TABLE [USERS]
DROP CONSTRAINT PK_ID_USERNAME
GO

ALTER TABLE [USERS]
ADD CONSTRAINT PK_ID PRIMARY KEY (ID)
GO

ALTER TABLE [USERS]
ADD CONSTRAINT UQ_USERNAME UNIQUE (USERNAME)
GO

ALTER TABLE [USERS]
ADD CONSTRAINT CK_USERNAME_LENGTH CHECK (DATALENGTH([USERNAME]) >=3)
GO