CREATE TABLE IF NOT EXISTS
	brands(
		id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name VARCHAR(50) UNIQUE NOT NULL
	)
;

CREATE TABLE IF NOT EXISTS
	classifications(
		id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name VARCHAR(30) UNIQUE NOT NULL
	)
;

CREATE TABLE IF NOT EXISTS
	customers(
		id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		first_name VARCHAR(30) NOT NULL,
		last_name VARCHAR(30) NOT NULL,
		address VARCHAR(150) NOT NULL,
		phone VARCHAR(30) UNIQUE NOT NULL,
		loyalty_card BOOLEAN DEFAULT FALSE NOT NULL
	)
;

CREATE TABLE IF NOT EXISTS
	items(
		id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		name VARCHAR(50) NOT NULL,
		quantity INT CHECK(quantity >= 0) NOT NULL,
		price DECIMAL (12,2) CHECK(price > 0.00) NOT NULL,
		description TEXT,
		brand_id INT REFERENCES brands(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
		classification_id INT REFERENCES classifications(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
	)
;

CREATE TABLE IF NOT EXISTS
	orders(
		id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		created_at TIMESTAMP DEFAULT NOW() NOT NULL,
		customer_id INT REFERENCES customers(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
	)
;

CREATE TABLE IF NOT EXISTS
	reviews(
		customer_id INT REFERENCES customers(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
		item_id INT REFERENCES items(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
		created_at TIMESTAMP DEFAULT NOW() NOT NULL,
		rating DECIMAL(3,1) DEFAULT 0.0 CHECK(rating <= 10.0) NOT NULL,
		CONSTRAINT pk_customer_id_item_id
		PRIMARY KEY (customer_id, item_id)
	)
;

CREATE TABLE IF NOT EXISTS
	orders_items(
		order_id INT REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
		item_id INT REFERENCES items(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
		quantity INT CHECK(quantity >= 0) NOT NULL,
		CONSTRAINT pk_order_id_item_id
		PRIMARY KEY (order_id, item_id)
	)
;